fullnameOverride: alerta

read:
  route:
    enabled: true
    host: alerta-read.example.local

web:
  route:
    enabled: true
    host: alerta-web.example.local

alertaAdminUsers:
  - admin
alertaAdminPassword: admin

alertaConfig: |
  DATABASE_URL = 'mongodb://alerta:alerta@mongodb.example.local:3717/alerta'
  CORS_ORIGINS = [r'https?://.*\.example\.local']

webConfig: |
  {
    "endpoint": "http://alerta-read.example.local"
  }

postgresql:
  enabled: false
